---
- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat


- name: Create a directory...
  file: path=/etc/filebeat/con.d  state=directory


- name: Upload a file...
  copy:
    src: "/home/jenkins/{{ file_name }}"
    dest: /etc/filebeat/conf.d/
