---
- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat


- name: Create a directory...
  file: path=/etc/filebeat/conf.d  state=directory


#- name: Upload a file...
#  copy:
#    src: "/home/vagrant/{{ file_name }}"
#    dest: /etc/filebeat/conf.d/
