---

- name: To install filebeat in RedHat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.6.3-x86_64.rpm
    state: present

- name: To create Directory
  file: path=/etc/filebeat/conf.d state=directory

- name: To setup filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: To start and enable Filebeat
  service:
    name: filebeat
    state: started
    enabled: true
