---
- name: Ensure dependency is installed (Ubuntu).
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.5.1-amd64.deb 
    state: present
 # apt: name=apt-transport-https state=present

- name: Install a .deb package from the internet.
  apt:
    deb: filebeat-5.5.1-amd64.deb
