---
- name: Add Filebeat GPG key.
  uri:
     url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.5.1-x86_64.rpm
     
 

- name: Add Filebeat repository.
  template:
    src: beats.repo.j2
    dest: /etc/yum.repos.d/beats.repo
    mode: 0644
